# Generated by Django 3.2.3 on 2021-06-01 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('total_cases', models.IntegerField(default=-1)),
                ('current_cases', models.IntegerField(default=-1)),
                ('recoveries', models.IntegerField(default=-1)),
                ('deaths', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stats.location')),
                ('iso', models.CharField(default='N/A', max_length=3)),
            ],
            bases=('stats.location',),
        ),
        migrations.AddField(
            model_name='location',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.time'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stats.location')),
                ('coordinates', models.CharField(max_length=3)),
                ('in_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.country')),
            ],
            bases=('stats.location',),
        ),
    ]
