# Generated by Django 3.2.3 on 2021-06-14 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', editable=False, max_length=20)),
                ('total_cases', models.IntegerField(default=-1)),
                ('active', models.IntegerField(default=-1)),
                ('recoveries', models.IntegerField(default=-1)),
                ('deaths', models.IntegerField(default=-1)),
                ('confirmed', models.IntegerField(default=-1)),
                ('iso', models.CharField(default='N/A', editable=False, max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Last_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='2019-12-31', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', editable=False, max_length=20)),
                ('total_cases', models.IntegerField(default=-1)),
                ('active', models.IntegerField(default=-1)),
                ('recoveries', models.IntegerField(default=-1)),
                ('deaths', models.IntegerField(default=-1)),
                ('confirmed', models.IntegerField(default=-1)),
                ('coordinates', models.CharField(max_length=3)),
                ('in_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.country')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', editable=False, max_length=20)),
                ('total_cases', models.IntegerField(default=-1)),
                ('active', models.IntegerField(default=-1)),
                ('recoveries', models.IntegerField(default=-1)),
                ('deaths', models.IntegerField(default=-1)),
                ('confirmed', models.IntegerField(default=-1)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='country',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.time'),
        ),
    ]
